name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Run Streamlit app
        run: |
          nohup streamlit run a/pages/4_예측 체험.py > streamlit.log 2>&1 &
