name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pip 업데이트
          pip install -r requirements.txt

      - name: Run Streamlit app
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          nohup streamlit run a/pages/4_예측 체험.py > streamlit.log 2>&1 &  # 로그 파일 지정
