jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - name: access to secrets
        run: |
          echo "API_KEY=$API_KEY" >> .env
        env:
          API_KEY: ${{secrets.API_KEY}}
